#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ybgin
#
# IDENTIFICATION
#    src/backend/access/ybgist/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ybgist
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ybgist.o ybgistget.o ybgistscan.o ybgistutil.o ybgistwrite.o

include $(top_srcdir)/src/backend/common.mk
